Repository codestates-seb/seb45_main_011, pull requests merged in 2023-08, with the labels that each got.

#1 [FE] 🔧 초기 환경 설정
  client/.eslintignore
  client/.eslintrc.json
  client/.gitignore
  client/.prettierignore
  client/.prettierrc
  client/README.md
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/next.svg
  client/public/vercel.svg
  client/src/app/favicon.ico
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/tailwind.config.ts
  client/tsconfig.json
Labels: Config

#11 [BE] ✨ profile 분리 및 백엔드 cicd
  .github/workflows/server.yml
  server/.gitignore
  server/Dockerfile
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: [BE], Config, Deploy

#12 [FE] 🔧 폰트 파일 전역 적용
  client/public/next.svg
  client/public/vercel.svg
  client/src/app/favicon.ico
  client/src/app/fonts/Galmuri11-Bold.woff2
  client/src/app/fonts/Galmuri11.woff2
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
Labels: Add, Config

#13 [FE] 🔧 초기 전역 스타일 설정
  client/src/tokens/tokens.ts
  client/tailwind.config.ts
Labels: Config

#14 [FE] 🍱 초기 에셋 파일 추가
  client/public/assets/icon/delete.svg
  client/public/assets/icon/edit.svg
  client/public/assets/icon/email.svg
  client/public/assets/icon/more.svg
  client/public/assets/icon/nickname.svg
  client/public/assets/icon/pw.svg
  client/public/assets/icon/pw_check.svg
  client/public/assets/img/bg_board_lg.svg
  client/public/assets/img/bg_board_md.svg
  client/public/assets/img/bg_board_sm.svg
  client/public/assets/img/bg_default.png
  client/public/assets/img/bg_garden.png
  client/public/assets/img/bg_grass.png
  client/public/assets/img/bg_paper.svg
  client/public/assets/img/bg_wood_dark.svg
  client/public/assets/img/bg_wood_light.svg
  client/public/assets/img/bg_wood_yellow.svg
  client/public/assets/img/bronze.svg
  client/public/assets/img/button_controller.svg
  client/public/assets/img/button_scroll.png
  client/public/assets/img/button_search.svg
  client/public/assets/img/comment.svg
  client/public/assets/img/gold.svg
  client/public/assets/img/like.svg
  client/public/assets/img/logo.svg
  client/public/assets/img/point.svg
  client/public/assets/img/screw.svg
  client/public/assets/img/silver.svg
  client/public/assets/img/trophy.svg
  client/src/tokens/tokens.js
Labels: Add, Fix

#15 [FE] ✨ 임시 라우팅 구현
  client/src/app/board/layout.tsx
  client/src/app/board/page.tsx
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leaf/layout.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/leafs/layout.tsx
  client/src/app/post/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/app/post/layout.tsx
  client/src/app/signin/layout.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/layout.tsx
  client/src/app/signup/page.tsx
  client/src/components/common/index.ts
  client/src/components/index.ts
  client/src/styles/globals.css
Labels: Feature, Config

#17 [FE] 🚀 배포 관련 환경 설정
  client/next.config.js
Labels: Config, Deploy

#21 [FE] ✨ Logo 컴포넌트 구현
  client/src/components/common/Logo.tsx
Labels: Feature

#28 [FE] ✨ ControlButton 컴포넌트 구현
  client/src/components/common/CommonButton.tsx
  client/src/components/common/ControlButton.tsx
  client/src/constants/contents.ts
  client/src/tokens/tokens.js
Labels: Feature, Fix, Config
