Repository codestates-seb/seb45_main_011, pull requests merged in 2023-11, with the labels that each got.

#320 🐛 Fix: AccountService.isAuthIdMatching 사용자 일치 여부 로직 개선
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
Labels: [BE] 이승태, Fix

#323 ✨ Feat : Guest Mode 기능 구현
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/account/constants/Status.java
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/guest/service/GuestService.java
  server/src/main/java/com/growstory/domain/images/service/JournalImageService.java
  server/src/main/java/com/growstory/domain/journal/service/JournalService.java
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/global/auth/utils/CustomAuthorityUtils.java
  server/src/main/resources/application-prod.yml
  server/src/main/resources/images/test1.jpg
  server/src/main/resources/images/test2.jpg
Labels: [BE] 황도경, [BE], Refactoring, 기능, Feature

#324 ♻️Refactoring : Guest Mode - Guest Email, DisplayName 저장 방식 변경
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/guest/service/GuestService.java
  server/src/main/java/com/growstory/global/email/service/EmailService.java
Labels: [BE] 황도경, [BE], Refactoring

#326 🐛 Fix : S3 region 변경으로 인한 업로드 이슈 해결Dev be
  .github/workflows/server.yml
  server/Dockerfile
  server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/growstory/global/aws/config/S3Config.java
  server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
Labels: [BE] 이승태, [BE], Fix, Config, Deploy

#327 [BE] ✨ Feat : 실시간 채팅 구현
  server/build.gradle
  server/server_log
  server/server_log.2023-10-04.0.gz
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/images/entity/ChatMessageImage.java
  server/src/main/java/com/growstory/domain/images/repository/ChatMessageImageRepository.java
  server/src/main/java/com/growstory/domain/images/service/ChatMessageImageService.java
  server/src/main/java/com/growstory/domain/images/service/JournalImageService.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/constant/ChatMessageConstants.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageStompController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/dto/ChatMessageRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/dto/ChatMessageResponseDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/entity/ChatMessage.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/mapper/ChatMessageMapper.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/repository/ChatMessageRepository.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageService.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageServiceImpl.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/constants/ChatRoomConstants.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/controller/ChatRoomController.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/ChatRoomRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/ChatRoomResponseDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/CreateQnaChatRequest.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/DeleteChatRoomRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/EntryCheckRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/EntryCheckResponseDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/entity/AccountChatRoom.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/entity/ChatRoom.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/repository/AccountChatRoomRepository.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/repository/ChatRoomRepository.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomService.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomServiceImpl.java
  server/src/main/java/com/growstory/global/config/WebSocketConfig.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
  server/src/main/java/com/growstory/global/response/PageResponse.java
Labels: [BE] 이승태, [BE], settings, Feature

#334 ♻️ Refactor : 게스트 계정 알림 추가, 일반 회원 가입 reportNum 초기화, Cors 설정
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java
Labels: [BE] 황도경, [BE], Refactoring, Config

#338 ♻️ Refactor : 게스트 회원 가입 토큰 추가
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/guest/service/GuestService.java
  server/src/main/java/com/growstory/domain/plant_object/entity/PlantObj.java
Labels: [BE] 황도경, [BE], Refactoring, Fix

#339 [BE] ✨ Feat : 실시간 채팅 구현
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/images/entity/ChatMessageImage.java
  server/src/main/java/com/growstory/domain/images/repository/ChatMessageImageRepository.java
  server/src/main/java/com/growstory/domain/images/service/ChatMessageImageService.java
  server/src/main/java/com/growstory/domain/images/service/JournalImageService.java
  server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/constant/ChatMessageConstants.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageStompController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/dto/ChatMessageRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/dto/ChatMessageResponseDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/entity/ChatMessage.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/mapper/ChatMessageMapper.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/repository/ChatMessageRepository.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageService.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageServiceImpl.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/constants/ChatRoomConstants.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/controller/ChatRoomController.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/ChatRoomRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/ChatRoomResponseDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/CreateQnaChatRequest.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/DeleteChatRoomRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/EntryCheckRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/entity/AccountChatRoom.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/entity/ChatRoom.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/repository/AccountChatRoomRepository.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/repository/ChatRoomRepository.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomService.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomServiceImpl.java
  server/src/main/java/com/growstory/global/utils/UriCreator.java
  server/src/main/java/com/growstory/global/websocket/FilterChannelInterceptor.java
  server/src/main/java/com/growstory/global/websocket/WebSocketConfig.java
  server/src/test/java/com/growstory/domain/journal/JournalControllerTest.java
Labels: [BE] 이승태, Refactoring, Feature, Fix

#340 [BE] ✨ 실시간 채팅 구현
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/constant/ChatMessageConstants.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageStompController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageService.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageServiceImpl.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/controller/ChatRoomController.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/CreateQnaChatResponse.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/EnumChatRoomRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/entity/ChatRoom.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomService.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomServiceImpl.java
  server/src/main/java/com/growstory/global/badwords/aspect/BadWordsAspect.java
  server/src/main/java/com/growstory/global/badwords/dto/ProfanityDto.java
  server/src/main/java/com/growstory/global/badwords/service/BlackListService.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
  server/src/main/java/com/growstory/global/response/ErrorResponse.java
  server/src/main/java/com/growstory/global/websocket/FilterChannelInterceptor.java
  server/src/main/java/com/growstory/global/websocket/WebSocketConfig.java
Labels: [BE] 이승태, Refactoring, Feature
