Repository codestates-seb/seb45_main_011, pull requests merged in 2023-10, with the labels that each got.

#295 [FE] ♻ 리팩토링을 위한 초기 작업 완료
  client/src/app/post/[id]/page.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/board/RankBoard.tsx
  client/src/components/common/ShareButton.tsx
  client/src/components/common/index.ts
  client/src/components/main/ServiceInfo.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/constants/values.ts
  client/src/stores/modalStore.ts
Labels: [FE], Refactoring, Fix

#303 [FE] ♻️ Garden 페이지 관련 리팩토링
  client/src/api/base.ts
  client/src/api/garden.ts
  client/src/app/garden/[id]/page.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/ShareModal.tsx
  client/src/components/garden/EmptyInventoryModal.tsx
  client/src/components/garden/GardenInfo.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSidebar.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/NoLeafExistModal.tsx
  client/src/components/garden/PlantCard.tsx
  client/src/components/garden/PurchaseInfoModal.tsx
  client/src/components/garden/PurchaseModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/post/PostForm.tsx
  client/src/hooks/useAddPostMutation.ts
  client/src/hooks/useEditPostMutation.ts
  client/src/hooks/usePlants.ts
  client/src/stores/gardenModalStore.ts
  client/src/stores/modalStore.ts
Labels: [FE], Refactoring

#308 [FE] ♻ hooks 폴더 구조 정리
  client/src/api/base.ts
  client/src/api/garden.ts
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/components/board/PostList.tsx
  client/src/components/board/SearchList.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/history/ConfirmModal.tsx
  client/src/components/leaf/DiaryDeleteModal.tsx
  client/src/components/leaf/DiaryForm.tsx
  client/src/components/leafs/LeafDeleteModal.tsx
  client/src/components/post/Comment.tsx
  client/src/components/post/CommentDeleteModal.tsx
  client/src/components/post/CommentForm.tsx
  client/src/components/post/PostForm.tsx
  client/src/hooks/mutation/useAddCommentMutation.ts
  client/src/hooks/mutation/useAddLeafMutaion.ts
  client/src/hooks/mutation/useAddPostMutation.ts
  client/src/hooks/mutation/useConnectLeafMutation.ts
  client/src/hooks/mutation/useDeleteCommentMutation.ts
  client/src/hooks/mutation/useDeleteDiaryMutaion.ts
  client/src/hooks/mutation/useDeleteLeafMutaion.ts
  client/src/hooks/mutation/useDeleteUser.ts
  client/src/hooks/mutation/useDiaryFormMutaion.ts
  client/src/hooks/mutation/useEditCommentMutation.ts
  client/src/hooks/mutation/useEditLeafMutation.ts
  client/src/hooks/mutation/useEditPostMutation.ts
  client/src/hooks/mutation/useLikePostMutation.ts
  client/src/hooks/mutation/useSaveGarden.ts
  client/src/hooks/query/useBoardInfinityQuery.ts
  client/src/hooks/query/useBoardSearchQuery.ts
  client/src/hooks/query/useLeafPageQueries.ts
  client/src/hooks/query/useLeafsPageQueries.ts
  client/src/hooks/useGardenMap.ts
  client/src/stores/signModalStore.ts
Labels: [FE], Refactoring

#310 [FE] ✨ axios 컴포넌트 구현 및 react query hooks 네이밍 리팩토링
  client/src/api/axios.ts
  client/src/api/history.ts
  client/src/api/profile.ts
  client/src/components/history/ConfirmModal.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/hooks/mutation/useAuthEmailMutation.ts
  client/src/hooks/mutation/useChangeImageMutation.ts
  client/src/hooks/mutation/useChangeNicknameMutation.ts
  client/src/hooks/mutation/useChangePasswordMutation.ts
  client/src/hooks/mutation/useDeleteUserMutation.ts
  client/src/hooks/mutation/useResignCheckMutation.ts
  client/src/hooks/mutation/useSigninMutation.ts
  client/src/hooks/mutation/useSignupMutation.ts
  client/src/hooks/query/useHistoryBoardQuery.ts
  client/src/hooks/query/useHistoryCommentQuery.ts
  client/src/hooks/query/useHistoryLikesQuery.ts
  client/src/hooks/query/useUserInfoQuery.ts
  client/src/hooks/useFindPassword.ts
  client/src/stores/userStore.ts
Labels: [FE], Refactoring, Feature

#317 [BE] ✨ Feat : 비속어 필터링 기능 구현
  server/src/main/java/com/growstory/GrowstoryApplication.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/comment/dto/CommentDto.java
  server/src/main/java/com/growstory/domain/journal/dto/JournalDto.java
  server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/growstory/global/badwords/aspect/BadWordsAspect.java
  server/src/main/java/com/growstory/global/badwords/dto/ProfanityDto.java
  server/src/main/java/com/growstory/global/badwords/dto/TextContainer.java
  server/src/main/java/com/growstory/global/badwords/filterlist/BlackList.java
  server/src/main/java/com/growstory/global/badwords/filterlist/WhiteList.java
  server/src/main/java/com/growstory/global/badwords/service/BlackListService.java
  server/src/main/java/com/growstory/global/exception/BusinessLogicException.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
  server/src/main/java/com/growstory/global/response/ErrorResponse.java
  server/src/test/java/com/growstory/domain/plant_object/controller/PlantObjectControllerTest.java
  server/src/test/java/com/growstory/domain/plant_object/service/PlantObjServiceTest.java
Labels: [BE] 이승태, [BE]
