Repository codestates-seb/seb45_main_011, pull requests merged in 2023-09, with the labels that each got.

#32 [FE] ✨ Header, HeaderLink 컴포넌트 구현
  .github/workflows/client.yml
  client/src/app/board/layout.tsx
  client/src/app/garden/[id]/layout.tsx
  client/src/app/leaf/layout.tsx
  client/src/app/leafs/layout.tsx
  client/src/app/page.tsx
  client/src/app/post/layout.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/HeaderLink.tsx
  client/tailwind.config.ts
Labels: [FE], Styling, Feature

#34 [FE] 🔧 누락된 스타일링 관련 환경 설정
  client/.prettierrc.json
  client/public/assets/img/bg_board_lg.png
  client/public/assets/img/bg_board_lg.svg
  client/public/assets/img/bg_board_md.png
  client/public/assets/img/bg_board_md.svg
  client/public/assets/img/bg_board_sm.png
  client/public/assets/img/bg_board_sm.svg
  client/public/assets/img/bg_paper.png
  client/public/assets/img/bg_paper.svg
  client/public/assets/img/bg_wood_dark.png
  client/public/assets/img/bg_wood_dark.svg
  client/public/assets/img/bg_wood_light.png
  client/public/assets/img/bg_wood_light.svg
  client/public/assets/img/bg_wood_yellow.png
  client/public/assets/img/bg_wood_yellow.svg
  client/src/components/common/CommonButton.tsx
  client/src/styles/globals.css
  client/src/tokens/tokens.js
Labels: Add, Fix, Config

#53 [FE] ♻️ Header 컴포넌트 리팩토링
  client/package-lock.json
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/HeaderLink.tsx
  client/src/constants/contents.ts
Labels: [FE], Refactoring

#54 [FE] ♻️ Intro 컴포넌트 리팩토링
  client/src/components/common/Intro.tsx
  client/src/constants/contents.ts
  client/src/styles/globals.css
Labels: Refactoring

#55 [FE] ♻️ Logo 컴포넌트 리팩토링
  client/src/app/layout.tsx
  client/src/components/common/Logo.tsx
Labels: Refactoring

#56 [FE] ✨ Modal, Screws 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/Screws.tsx
  client/src/styles/globals.css
Labels: Feature, Fix, Config

#57 [FE] ✨ PageTitle 컴포넌트 구현
  client/src/app/layout.tsx
  client/src/components/common/PageTitle.tsx
Labels: Feature

#58 [FE] 🐛 Logo 컴포넌트 라우팅 추가
  client/src/components/common/Logo.tsx
Labels: Fix

#60 [FE] ✨ MapController 컴포넌트 구현
  client/public/assets/img/button_controller.svg
  client/public/assets/img/button_controller_down.png
  client/public/assets/img/button_controller_left.png
  client/public/assets/img/button_controller_right.png
  client/public/assets/img/button_controller_up.png
  client/src/components/MapController.tsx
  client/src/components/common/ControlButton.tsx
  client/src/constants/contents.ts
  client/src/constants/values.ts
  client/src/styles/globals.css
Labels: Styling, Feature, Fix, Config

#61 [FE] ✨ Plant 컴포넌트 구현
  client/next.config.js
  client/src/components/Plant.tsx
  client/src/mock/products.json
  client/src/utils/getPlantSize.ts
Labels: Test, Feature, Config

#62 [FE] ✨ PlantCard 컴포넌트 구현
  client/src/components/Plant.tsx
  client/src/components/PlantCard.tsx
  client/src/components/common/CommonButton.tsx
  client/src/constants/contents.ts
  client/src/styles/globals.css
  client/src/types/common.d.ts
Labels: Feature, Config

#63 [FE] ✨ EditButton 컴포넌트 구현
  client/src/components/EditButton.tsx
  client/src/tokens/tokens.js
Labels: Styling, Feature, Config

#64 [FE] ✨ Leaf 컴포넌트 구현
  client/next.config.js
  client/public/assets/img/checked.svg
  client/src/components/common/Leaf.tsx
  client/src/components/common/LeafName.tsx
  client/src/mock/leaf.json
  client/src/types/common.d.ts
Labels: Feature, Config

#65 [FE] ✨ AddLeafButton 컴포넌트 구현
  client/public/assets/img/plus.svg
  client/src/components/AddLeafButton.tsx
Labels: Feature

#66 [BE] ✨ Feat: account 관련 기능 구현
  server/build.gradle
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/point/entity/Point.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/growstory/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/growstory/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
  server/src/main/java/com/growstory/global/aws/config/S3Config.java
  server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
  server/src/main/java/com/growstory/global/email/controller/EmailController.java
  server/src/main/java/com/growstory/global/email/dto/EmailDto.java
  server/src/main/java/com/growstory/global/email/service/EmailService.java
  server/src/main/java/com/growstory/global/utils/UriCreator.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
  server/src/main/resources/templates/authCode.html
  server/src/main/resources/templates/password.html
Labels: [BE] 김도형, Feature

#18 [BE] 🚀 RDS 환경 변수 설정
  .github/workflows/server.yml
  server/Dockerfile
  server/build.gradle
  server/src/main/java/com/growstory/HelloController.java
  server/src/main/resources/application-dev.yml
  server/src/main/resources/application-prod.yml
  server/src/main/resources/application.yml
Labels: [BE] 황도경, Config, Deploy

#68 [FE] ✨ LeafDiary 컴포넌트 구현
  client/src/components/Diary.tsx
  client/src/components/EmptyDiary.tsx
  client/src/components/LeafDiary.tsx
  client/src/components/common/Leaf.tsx
  client/src/mock/diary.json
  client/src/types/common.d.ts
Labels: Feature

#69 [FE] ✨ SignInput 컴포넌트 구현
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/HeaderLink.tsx
  client/src/components/common/SignInput.tsx
  client/src/components/sign/signin/SigninForm.tsx
  client/src/components/sign/signin/SigninTextBox.tsx
  client/src/components/sign/signup/SignupForm.tsx
  client/src/components/sign/signup/SignupTextBox.tsx
  client/src/constants/contents.ts
Labels: [FE], Feature

#71 [BE] ✨ Feat: image 업로드, 삭제 기능 구현
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
  server/src/main/resources/application-local.yml
Labels: [BE] 김도형, Feature

#74 [FE] ✨ImageInput 컴포넌트 구현
  client/public/assets/img/snow_tree.svg
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/HeaderLink.tsx
  client/src/components/common/ImageInput.tsx
  client/src/components/common/SignInput.tsx
  client/src/components/sign/signin/SigninTextBox.tsx
  client/src/components/sign/signup/SignupTextBox.tsx
Labels: [FE], Styling, Add

#75 [FE] ✨ LeafInfo 컴포넌트 구현
  client/src/components/Diary.tsx
  client/src/components/LeafDiary.tsx
  client/src/components/LeafInfo.tsx
  client/src/components/common/PageTitle.tsx
  client/src/mock/leaf.json
  client/src/types/common.d.ts
Labels: Styling, Feature

#79 [FE] ✨ LeafTag 컴포넌트 구현
  client/src/components/LeafTag.tsx
  client/src/styles/globals.css
Labels: Feature

#81 [FE] ✨ GardenSidebar 컴포넌트 구현, ♻ 기존 컴포넌트 리팩토링
  client/src/components/GardenSidebar.tsx
  client/src/components/Plant.tsx
  client/src/components/PlantCard.tsx
  client/src/components/common/CommonButton.tsx
  client/src/components/common/ControlButton.tsx
  client/src/constants/contents.ts
  client/src/mock/products.json
  client/src/styles/globals.css
  client/src/types/common.d.ts
  client/src/utils/getPlantSize.ts
Labels: Refactoring, Styling, Test, Feature, Fix

#82 [BE] ✨ Feat: leaf 관련 기능 구현
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/leaf/repository/LeafRepository.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/domain/point/entity/Point.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
  server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
Labels: [BE] 김도형, Feature

#83 [FE] ✨ ConnectCheckBox 컴포넌트 구현
  client/src/components/common/ConnectCheckBox.tsx
Labels: [FE], Add, Feature

#85 [BE] ✨ Feat: garden 관련 기능 구현
  server/build.gradle
  server/gradlew
  server/gradlew.bat
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/images/entity/BoardImage.java
  server/src/main/java/com/growstory/domain/images/entity/Image.java
  server/src/main/java/com/growstory/domain/images/entity/JournalImage.java
  server/src/main/java/com/growstory/domain/journal/entity/Journal.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/leaf/mapper/LeafMapper.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/domain/location/entity/Location.java
  server/src/main/java/com/growstory/domain/plant_object/controller/PlantObjController.java
  server/src/main/java/com/growstory/domain/plant_object/dto/PlantObjDto.java
  server/src/main/java/com/growstory/domain/plant_object/entity/PlantObj.java
  server/src/main/java/com/growstory/domain/plant_object/location/dto/LocationDto.java
  server/src/main/java/com/growstory/domain/plant_object/location/entity/Location.java
  server/src/main/java/com/growstory/domain/plant_object/location/mapper/LocationMapper.java
  server/src/main/java/com/growstory/domain/plant_object/location/repository/LocationRepository.java
  server/src/main/java/com/growstory/domain/plant_object/location/service/LocationService.java
  server/src/main/java/com/growstory/domain/plant_object/mapper/PlantObjMapper.java
  server/src/main/java/com/growstory/domain/plant_object/repository/PlantObjRepository.java
  server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
  server/src/main/java/com/growstory/domain/point/entity/Point.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/domain/product/entity/Product.java
  server/src/main/java/com/growstory/domain/product/repository/ProductRepository.java
  server/src/main/java/com/growstory/domain/product/service/ProductService.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: [BE] 이승태, [BE], Feature

#89 [FE] ✨ Input, TextArea 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/components/common/HashTag.tsx
  client/src/components/common/PasswordInput.tsx
  client/src/components/common/TagInputForm.tsx
  client/src/components/common/TextArea.tsx
  client/src/components/common/TextInput.tsx
  client/src/types/common.d.ts
Labels: Feature

#91 [BE] ♻️ Refactor : 이메일 관련 코드 리팩토링
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/domain/point/entity/Point.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
  server/src/main/java/com/growstory/global/email/controller/EmailController.java
  server/src/main/java/com/growstory/global/email/dto/EmailDto.java
  server/src/main/java/com/growstory/global/email/service/EmailService.java
  server/src/main/resources/application-dev.yml
  server/src/main/resources/templates/authCode.html
  server/src/main/resources/templates/password.html
Labels: [BE] 김도형, Refactoring

#92 [FE] ✨ GardenMap 컴포넌트 구현
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/components/EditButton.tsx
  client/src/components/EditModeButton.tsx
  client/src/components/EditModeInfo.tsx
  client/src/components/GardenMap.tsx
  client/src/components/GardenSidebar.tsx
  client/src/components/GardenSquares.tsx
  client/src/components/InstalledPlants.tsx
  client/src/components/MapController.tsx
  client/src/components/Plant.tsx
  client/src/components/PlantCard.tsx
  client/src/components/TrackedPlant.tsx
  client/src/constants/values.ts
  client/src/hooks/useMouseTrack.ts
  client/src/mock/garden.json
  client/src/mock/products.json
  client/src/stores/gardenStore.ts
  client/src/styles/globals.css
  client/src/tokens/tokens.js
  client/src/types/common.d.ts
  client/src/types/data.d.ts
  client/src/utils/getInitialMapInfo.ts
  client/src/utils/getInstallable.ts
  client/src/utils/getPlantOpacity.ts
Labels: Styling, Test, Feature, Config

#96 [BE] ♻️ Refactor : Leaf 관련 코드 리팩토링
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
Labels: [BE] 김도형, Refactoring

#98 🐛 Garden 페이지 관련 기능 오류 수정, ✨ ModalPortal 컴포넌트 구현
  client/src/app/garden/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/components/GardenMap.tsx
  client/src/components/GardenSquares.tsx
  client/src/components/InstalledPlants.tsx
  client/src/components/PlantCard.tsx
  client/src/components/TrackedPlant.tsx
  client/src/components/common/ModalPortal.tsx
  client/src/mock/garden.json
  client/src/stores/gardenStore.ts
  client/src/types/common.d.ts
  client/src/types/data.d.ts
  client/src/utils/getInitialMapInfo.ts
  client/src/utils/getPlantOpacity.ts
Labels: Styling, Test, Feature, Fix

#99 [FE] ✨ Garden 페이지, 관련 Modal 컴포넌트 구현
  .gitignore
  client/next.config.js
  client/public/assets/icon/checked.svg
  client/public/assets/icon/installable.svg
  client/public/assets/icon/uninstallable.svg
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/components/EditModeButton.tsx
  client/src/components/GardenMap.tsx
  client/src/components/GardenSidebar.tsx
  client/src/components/InstalledPlants.tsx
  client/src/components/InventoryEmptyModal.tsx
  client/src/components/LeafConnectModal.tsx
  client/src/components/LeafTag.tsx
  client/src/components/PlantCard.tsx
  client/src/components/PurchaseInfoModal.tsx
  client/src/components/PurchaseModal.tsx
  client/src/components/SelectLeafModal.tsx
  client/src/components/TrackedPlant.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/LeafName.tsx
  client/src/components/common/Modal.tsx
  client/src/stores/gardenStore.ts
  client/src/stores/modalStore.ts
  client/src/styles/globals.css
Labels: Styling, Test, Feature, Fix, Config

#100 [FE] ✨ Signup 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/app/api/auth/[...nextauth]/route.ts
  client/src/app/auth/[...nextauth]/route.ts
  client/src/app/layout.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/sign/signin/FindPassword.tsx
  client/src/components/sign/signin/SigninForm.tsx
  client/src/components/sign/signin/SigninTextBox.tsx
  client/src/components/sign/signup/AuthenticateEmail.tsx
  client/src/components/sign/signup/SignupForm.tsx
  client/src/components/sign/signup/SignupTextBox.tsx
  client/src/constants/contents.ts
  client/src/context/AuthContext.tsx
  client/src/types/common.d.ts
Labels: [FE], Feature

#103 [FE] ♻️ Garden 페이지 1차 리팩토링
  client/package-lock.json
  client/package.json
  client/src/api/client.ts
  client/src/api/garden.ts
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/components/EditModeButton.tsx
  client/src/components/LeafConnectModal.tsx
  client/src/components/common/CommonButton.tsx
  client/src/components/garden/EditModeButton.tsx
  client/src/components/garden/EditModeInfo.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSidebar.tsx
  client/src/components/garden/GardenSquares.tsx
  client/src/components/garden/InstalledPlants.tsx
  client/src/components/garden/InventoryEmptyModal.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/MapController.tsx
  client/src/components/garden/NoLeafExistModal.tsx
  client/src/components/garden/Plant.tsx
  client/src/components/garden/PlantCard.tsx
  client/src/components/garden/PurchaseInfoModal.tsx
  client/src/components/garden/PurchaseModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/garden/TrackedPlant.tsx
  client/src/components/garden/index.ts
  client/src/mock/garden.json
  client/src/stores/gardenModalStore.ts
  client/src/stores/gardenStore.ts
  client/src/stores/modalStore.ts
  client/src/types/common.d.ts
  client/src/types/data.d.ts
  client/src/utils/getInitialMapInfo.ts
Labels: Refactoring, Feature, Config

#105 [BE] 식물 일지 CRUD 기능 구현
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/images/entity/JournalImage.java
  server/src/main/java/com/growstory/domain/images/repository/JournalImageRepository.java
  server/src/main/java/com/growstory/domain/images/service/JournalImageService.java
  server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
  server/src/main/java/com/growstory/domain/journal/dto/JournalDto.java
  server/src/main/java/com/growstory/domain/journal/entity/Journal.java
  server/src/main/java/com/growstory/domain/journal/mapper/JournalMapper.java
  server/src/main/java/com/growstory/domain/journal/repository/JournalRepository.java
  server/src/main/java/com/growstory/domain/journal/service/JournalService.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/domain/plant_object/dto/PlantObjDto.java
  server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
Labels: [BE] 이승태, Refactoring, 기능, Fix

#107 [BE]♻️ Refactor : 정원 CRUD 응답 데이터 수정
  server/src/main/java/com/growstory/domain/plant_object/controller/PlantObjController.java
  server/src/main/java/com/growstory/domain/plant_object/dto/PlantObjDto.java
  server/src/main/java/com/growstory/domain/plant_object/entity/PlantObj.java
  server/src/main/java/com/growstory/domain/plant_object/location/mapper/LocationMapper.java
  server/src/main/java/com/growstory/domain/plant_object/mapper/PlantObjMapper.java
  server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
  server/src/main/java/com/growstory/domain/product/controller/ProductController.java
  server/src/main/java/com/growstory/domain/product/dto/ProductDto.java
  server/src/main/java/com/growstory/domain/product/entity/Product.java
  server/src/main/java/com/growstory/domain/product/mapper/ProductMapper.java
  server/src/main/java/com/growstory/domain/product/service/ProductService.java
  server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
Labels: [BE] 이승태, Refactoring

#109 [FE/BE] ♻ Garden 페이지 2차 리팩토링
  client/package-lock.json
  client/src/app/garden/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/components/garden/EditModeButton.tsx
  client/src/components/garden/EmptyInventoryModal.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSquares.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/PlantCard.tsx
  client/src/components/garden/PurchaseInfoModal.tsx
  client/src/components/garden/PurchaseModal.tsx
  client/src/components/garden/TrackedPlant.tsx
  client/src/components/garden/index.ts
  client/src/constants/values.ts
  client/src/hooks/useEffectOnce.ts
  client/src/hooks/useMouseTrack.ts
  client/src/hooks/usePlants.ts
  client/src/hooks/useRollback.ts
  client/src/hooks/useSquares.ts
  client/src/stores/gardenModalStore.ts
  client/src/stores/gardenStore.ts
  client/src/utils/createSquares.ts
Labels: Refactoring, Feature, Fix, Config

#110 [BE] ♻️ Refactor : Account 관련 기능 리팩토링
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/resources/application-prod.yml
Labels: [BE], Refactoring

#114 [FE] ♻ Leafs/Leaf 페이지 리팩토링
  client/src/api/LeafAPI.ts
  client/src/app/ReactQueryProvider.tsx
  client/src/app/layout.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/components/AddLeafButton.tsx
  client/src/components/Diary.tsx
  client/src/components/DiaryDeleteModal.tsx
  client/src/components/DiaryForm.tsx
  client/src/components/EmptyDiary.tsx
  client/src/components/LeafDeleteModal.tsx
  client/src/components/LeafDiary.tsx
  client/src/components/LeafInfo.tsx
  client/src/components/common/ImageUpload.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/Preview.tsx
  client/src/components/common/TextArea.tsx
  client/src/components/common/TextInput.tsx
  client/src/mock/leaf.json
  client/src/stores/leafStore.ts
  client/src/stores/leafStore.tsx
  client/src/stores/leafsStore.ts
  client/src/stores/modalStore.ts
  client/src/stores/userStore.ts
  client/src/types/common.d.ts
  client/src/types/data.d.ts
  client/src/utils/fileListToFormData.ts
Labels: Refactoring, Feature

#116 ✏️ Chore : JournalImageService.deleteJournalImageWithS3 주석 해제
  server/src/main/java/com/growstory/domain/images/service/JournalImageService.java
Labels: [BE] 이승태, Fix

#117 [BE] ♻️ Refactor : Leaf 관련 이미지 처리 리팩토링
  server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/resources/application.yml
Labels: [BE] 김도형, Refactoring

#121 🔧 Conf: prod.yml 환경설정 ddl-auto: create -> update
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
  server/src/main/resources/application-prod.yml
Labels: [BE], settings, Deploy

#123 ♻️ Refactor: 식물 일지 전체 조회 요청 데이터 변경
  .gitignore
  server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
  server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
Labels: [BE] 이승태, Refactoring

#124 [BE] ✨ Feat : security
  .github/workflows/server.yml
  server/Dockerfile
  server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
  server/src/main/resources/application-prod.yml
Labels: [BE] 김도형

#126 [BE] 댓글 기능 리팩토링
  server/src/main/java/com/growstory/domain/comment/service/CommentService.java
Labels: [BE] 황도경, [BE], Test, Fix

#130 ♻️ Refactor : Journal 목록 조회, Garden 응답 데이터 수정
  server/src/main/java/com/growstory/domain/journal/dto/JournalDto.java
  server/src/main/java/com/growstory/domain/journal/mapper/JournalMapper.java
  server/src/main/java/com/growstory/domain/journal/repository/JournalRepository.java
  server/src/main/java/com/growstory/domain/journal/service/JournalService.java
  server/src/main/java/com/growstory/domain/plant_object/location/dto/LocationDto.java
Labels: [BE] 이승태, Refactoring

#131 🐛 Fix : Journal 목록 식물 관리 카드별 조회
  server/src/main/java/com/growstory/domain/journal/service/JournalService.java
  server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/growstory/global/response/ErrorResponder.java
Labels: [BE] 이승태, Fix

#132 [FE] ✨ Garden 페이지 API 연결, ♻ Garden 페이지 3차 리팩토링
  client/src/api/garden.ts
  client/src/app/garden/[id]/page.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/garden/EditModeButton.tsx
  client/src/components/garden/EmptyInventoryModal.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSidebar.tsx
  client/src/components/garden/InstalledPlants.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/MapController.tsx
  client/src/components/garden/NoLeafExistModal.tsx
  client/src/components/garden/PlantCard.tsx
  client/src/components/garden/PurchaseInfoModal.tsx
  client/src/components/garden/PurchaseModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/garden/TrackedPlant.tsx
  client/src/hooks/useArchive.ts
  client/src/hooks/useConnectLeaf.ts
  client/src/hooks/useGardenMap.ts
  client/src/hooks/usePlantCard.ts
  client/src/hooks/usePlants.ts
  client/src/hooks/usePurchasePlant.ts
  client/src/hooks/useRollback.ts
  client/src/hooks/useSaveGarden.ts
  client/src/hooks/useSquares.ts
  client/src/hooks/useSyncGarden.ts
  client/src/mock/garden.json
  client/src/stores/gardenStore.ts
  client/src/stores/userStore.ts
  client/src/types/common.d.ts
  client/src/types/data.d.ts
  client/src/utils/createInventory.ts
Labels: Refactoring, Test, Feature, Fix

#134 [BE] ♻️ Refactor : Account 관련 기능 리팩토링
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
Labels: [BE] 김도형, Refactoring

#136 [BE] ♻️ Refactor : Leaf, Account 관련 기능 리팩토링
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
Labels: [BE] 김도형, Refactoring

#137 [BE] ♻️ Refactor : Leaf 관련 기능 리팩토링
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/global/auth/dto/LoginDto.java
  server/src/main/java/com/growstory/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/resources/application-prod.yml
Labels: [BE] 김도형, Refactoring

#138 [FE] ✨ 2차 기능 개발 전 컨벤션 수립 및 적용
  client/src/api/client.ts
  client/src/api/leaf.ts
  client/src/app/board/layout.tsx
  client/src/app/board/page.tsx
  client/src/app/history/[id]/layout.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/layout.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/not-found.tsx
  client/src/app/profile/layout.tsx
  client/src/app/profile/page.tsx
  client/src/components/Leaf/DiaryDeleteModal.tsx
  client/src/components/Leaf/DiaryForm.tsx
  client/src/components/Leaf/LeafDiary.tsx
  client/src/components/Leafs/LeafDeleteModal.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/ReactQueryProvider.tsx
  client/src/stores/modalStore.ts
Labels: [FE], Refactoring, Feature

#144 [BE] ♻️ Refactor : Leaf 관련 기능 리팩토링
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
Labels: [BE] 김도형, Refactoring

#142 [FE] ♻️ Signin, Signup 페이지 리팩토링
  client/package-lock.json
  client/package.json
  client/src/api/user.ts
  client/src/app/layout.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/HeaderLink.tsx
  client/src/components/common/sign/SignInput.tsx
  client/src/components/common/sign/SignLink.tsx
  client/src/components/common/sign/SignModalInput.tsx
  client/src/components/common/sign/SignPasswordInput.tsx
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/components/signin/SuccessedModal.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/components/signup/SignupIntro.tsx
  client/src/stores/persistStore.ts
  client/src/stores/signModalStore.ts
  client/src/stores/signStore.ts
  client/src/styles/globals.css
  client/src/types/common.d.ts
Labels: [FE], Refactoring, Feature

#146 [BE] 🧪 Comment API Testing
  server/build.gradle
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/board/entity/Board.java
  server/src/main/java/com/growstory/domain/comment/dto/CommentDto.java
  server/src/main/java/com/growstory/domain/comment/entity/Comment.java
  server/src/main/java/com/growstory/domain/comment/service/CommentService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/growstory/domain/comment/controller/CommentControllerTest.java
Labels: [BE] 황도경, Test, Config

#152 [FE] ✨ Garden 페이지 공유 기능 구현
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/components/garden/InstalledPlants.tsx
  client/src/components/garden/LeafTag.tsx
  client/src/components/garden/NoLeafExistModal.tsx
  client/src/components/garden/index.ts
  client/src/hooks/usePlants.ts
  client/src/hooks/usePurchasePlant.ts
  client/src/hooks/useSyncGarden.ts
Labels: [FE], Refactoring, Feature

#149 [FE] ✨ Leafs, Leaf 페이지 공유 기능 구현
  client/src/api/leaf.ts
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/components/Leaf/Diary.tsx
  client/src/components/Leaf/EmptyDiary.tsx
  client/src/components/Leaf/LeafDateInfo.tsx
  client/src/components/Leaf/LeafDiary.tsx
  client/src/components/Leaf/LeafInfo.tsx
  client/src/components/Leaf/LeafModa.tsx
  client/src/components/Leafs/AddLeafButton.tsx
  client/src/components/Leafs/LeafDeleteModal.tsx
  client/src/components/common/ImageUpload.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/NoImage.tsx
  client/src/components/common/Preview.tsx
  client/src/components/common/ReactQueryProvider.tsx
  client/src/components/common/TextArea.tsx
  client/src/components/common/TextInput.tsx
  client/src/hooks/useAddLeafMutaion.ts
  client/src/hooks/useDeleteLeafMutaion.ts
  client/src/hooks/useEditLeafMutation.ts
  client/src/stores/leafStore.ts
  client/src/stores/testUserStore.ts
  client/src/utils/convertToFormData.ts
  client/src/utils/fileListToFormData.ts
  client/src/utils/getDayElapsed.ts
  client/src/utils/getTextAreaTypeFormat.ts
  client/src/utils/getTextInputTypeFormat.ts
  client/src/utils/isValidFileSize.ts
  client/src/utils/setPreview.ts
Labels: [FE], Refactoring, Feature

#154 [FE] ✨ Feat: Profile 페이지 구현중 (#147)
  client/package-lock.json
  client/src/api/profile.ts
  client/src/api/user.ts
  client/src/app/board/layout.tsx
  client/src/app/garden/[id]/layout.tsx
  client/src/app/history/[id]/layout.tsx
  client/src/app/layout.tsx
  client/src/app/leaf/layout.tsx
  client/src/app/leafs/[id]/layout.tsx
  client/src/app/not-found.tsx
  client/src/app/page.tsx
  client/src/app/post/layout.tsx
  client/src/app/profile/layout.tsx
  client/src/app/profile/page.tsx
  client/src/components/Leaf/EmptyDiary.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/ImageInput.tsx
  client/src/components/common/PasswordInput.tsx
  client/src/components/common/TextInput.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/profile/ProfileForm.tsx
  client/src/components/sign/SignInput.tsx
  client/src/components/sign/SignLink.tsx
  client/src/components/sign/SignModalInput.tsx
  client/src/components/sign/SignPasswordInput.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/components/signup/SignupIntro.tsx
  client/src/stores/persistStore.ts
Labels: [FE], Feature

#155 [BE] 🧪 Test : 도경 Comment 관련 기능 테스트, 도형 Account 관련 기능 테스트
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/resources/application.yml
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
Labels: [BE], Test

#156 [BE] ✨ Feat : Account 비밀번호 검증 api 추가
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
Labels: [BE] 김도형, Feature

#157 [FE] ✨ History 페이지 구현중
  client/public/assets/icon/down.svg
  client/public/assets/icon/up.svg
  client/public/assets/img/profile_hitmontop.png
  client/src/api/history.ts
  client/src/api/profile.ts
  client/src/app/history/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/ImageInput.tsx
  client/src/components/history/ComfirmModal.tsx
  client/src/components/history/Dropdown.tsx
  client/src/components/history/FailureModal.tsx
  client/src/components/history/HistoryForm.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/profile/ProfileForm.tsx
  client/src/components/sign/SignModalInput.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/stores/persistStore.ts
  client/src/stores/signStore.ts
  client/src/stores/userStore.ts
Labels: [FE], Add, Feature

#158 ✨ Feat : 일지 작성시 point 추가 및 Garden 조회 시 토큰 미검증
  server/src/main/java/com/growstory/domain/journal/service/JournalService.java
  server/src/main/java/com/growstory/domain/plant_object/dto/PlantObjDto.java
  server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
Labels: [BE] 이승태, [BE]

#159 [BE] ✨게시판 기능 구현
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/board/entity/Board_HashTag.java
  server/src/main/java/com/growstory/domain/board/repository/BoardHashTagResitory.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/hashTag/entity/HashTag.java
  server/src/main/java/com/growstory/domain/hashTag/repository/HashTagRepository.java
  server/src/main/java/com/growstory/domain/hashTag/service/HashTagService.java
Labels: [BE] 황도경, Feature

#161 [BE] ♻️ Refactor : Account 응답, Leaf 응답 리팩토링
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/board/controller/BoardController.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/global/auth/userdetails/AccountDetailsService.java
  server/src/main/java/com/growstory/global/util/UriCreator.java
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
  server/src/test/java/com/growstory/global/customUser/annotation/WithMockCustomUser.java
  server/src/test/java/com/growstory/global/customUser/factory/WithMockCustomUserSecurityContextFactory.java
  server/src/test/resources/images/testImage.jpg
Labels: [BE] 김도형, Refactoring

#162 [BE] ♻️ Refactor : Account 응답, Leaf 응답 리팩토링
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
Labels: [BE] 김도형, Refactoring

#163 [FE] ✨ Board 페이지 1차 구현
  client/package-lock.json
  client/package.json
  client/src/api/board.ts
  client/src/app/board/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/components/Leaf/LeafModal.tsx
  client/src/components/board/BoardBanner.tsx
  client/src/components/board/BoardSearchForm.tsx
  client/src/components/board/BoardSearchInput.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/board/PostList.tsx
  client/src/components/board/RankBoard.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/LeafName.tsx
  client/src/hooks/useBoardInfinityQuery.ts
  client/src/hooks/useGetBoardSearchQuery.ts
  client/src/mock/board.json
  client/src/stores/boardStore.ts
  client/src/styles/globals.css
  client/src/types/common.d.ts
  client/src/types/data.d.ts
Labels: [FE], Feature

#166 [BE] ♻️ Refactor : Account 응답, Like 리팩토링
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/likes/repository/BoardLikeRepository.java
  server/src/main/java/com/growstory/domain/likes/repository/CommentLikeRepository.java
  server/src/main/java/com/growstory/domain/likes/service/LikeService.java
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
  server/src/test/java/com/growstory/global/customUser/annotation/WithMockCustomUser.java
  server/src/test/java/com/growstory/global/customUser/factory/WithMockCustomUserSecurityContextFactory.java
Labels: [BE] 김도형, Refactoring

#164 [FE] ✨ Leafs, Leaf 공유 구현
  client/src/app/leafs/[id]/page.tsx
  client/src/types/data.d.ts
Labels: [FE], Feature

#167 [FE] ✨ 404 페이지 구현
  client/public/assets/img/warning.svg
  client/src/app/not-found.tsx
Labels: [FE], Add, Feature

#168 [FE] ✨ Post 페이지 하위의 add, edit 페이지, delete 기능 구현
  client/src/api/garden.ts
  client/src/api/post.ts
  client/src/app/garden/[id]/layout.tsx
  client/src/app/post/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/components/common/TagInput.tsx
  client/src/components/common/TagInputForm.tsx
  client/src/components/common/TextArea.tsx
  client/src/components/common/TextInput.tsx
  client/src/components/post/PostDeleteModal.tsx
  client/src/components/post/PostForm.tsx
  client/src/stores/gardenStore.ts
  client/src/stores/postModalStore.ts
  client/src/types/data.d.ts
Labels: [FE], Refactoring, Feature

#170 [FE] ✨ Loading 컴포넌트 구현
  client/public/assets/img/loading.png
  client/src/components/common/Loading.tsx
  client/src/constants/contents.ts
  client/src/hooks/useTyping.ts
  client/src/styles/globals.css
Labels: [FE], Styling, Add, Feature

#172 [BE] 🔧 Conf : Swagger Configuration
  server/build.gradle
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/global/config/SwaggerConfig.java
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
Labels: [BE], settings

#173 [FE] ✨ ErrorMessage 컴포넌트 구현
  client/public/assets/img/bg_default_post.png
  client/public/assets/img/bg_default_profile.png
  client/src/components/common/ErrorMessage.tsx
  client/src/components/common/LoadingMessage.tsx
Labels: [FE], Styling, Add, Feature

#175 [BE] 🔧 Conf : jacoco Configuration
  server/build.gradle
Labels: [BE], settings

#176 [BE] ✏️ Chore : Account, Leaf, Like Swagger 설정
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/likes/controller/LikeController.java
  server/src/main/java/com/growstory/global/email/controller/EmailController.java
  server/src/main/java/com/growstory/global/email/dto/EmailDto.java
Labels: [BE] 김도형

#177 [FE] ✨ History 페이지 1차 구현
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/assets/img/profile_hitmontop.png
  client/src/components/common/Header/Header.tsx
  client/src/components/history/Dropdown.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryForm.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/constants/contents.ts
  client/src/hooks/useDetectClose.ts
  client/src/stores/historyStore.ts
  client/src/stores/userStore.ts
  client/src/styles/globals.css
  client/tailwind.config.ts
Labels: [FE], Feature, Fix

#180 [FE] ✨ Post Page 1차 구현
  client/src/app/post/[id]/page.tsx
  client/src/components/board/BoardBanner.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/common/PageTitle.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/post/Comment.tsx
  client/src/components/post/CommentForm.tsx
  client/src/components/post/CommentProfileImage.tsx
  client/src/components/post/PostContent.tsx
  client/src/components/post/PostContolButton.tsx
  client/src/components/post/PostDateAndControl.tsx
  client/src/components/post/PostImage.tsx
  client/src/components/post/PostProfile.tsx
  client/src/styles/globals.css
  client/src/types/data.d.ts
Labels: [FE], Feature

#181 [FE] ✨ 반응형 1차 구현, 전체 CSS 다듬기
  client/src/app/board/layout.tsx
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/history/[id]/layout.tsx
  client/src/app/layout.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leaf/layout.tsx
  client/src/app/leafs/[id]/layout.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/page.tsx
  client/src/app/post/layout.tsx
  client/src/app/profile/layout.tsx
  client/src/app/signin/layout.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/layout.tsx
  client/src/app/signup/page.tsx
  client/src/components/common/CommonButton.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/HeaderLink.tsx
  client/src/components/common/Intro.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/Logo.tsx
  client/src/components/common/PageTitle.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSidebar.tsx
  client/src/components/garden/PlantCard.tsx
  client/src/components/sign/SignLink.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/components/signup/SignupIntro.tsx
  client/src/styles/globals.css
Labels: [FE], Styling, Feature, Config

#183 [BE] ♻️ Refactor : Account, Email, Leaf 관련 리팩토링
  server/build.gradle
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/resources/templates/authCode.html
  server/src/main/resources/templates/password.html
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
Labels: [BE] 김도형, Refactoring

#184 [BE] ♻️ Refactor : Account, Email, Leaf 관련 리팩토링
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
Labels: [BE] 김도형, Refactoring

#186 [BE] 🐛 게시판 전체 조회 OutOfIndex 해결
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/board/controller/BoardController.java
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/board/dto/ResponseBoardDto.java
  server/src/main/java/com/growstory/domain/board/dto/ResponseBoardPageDto.java
  server/src/main/java/com/growstory/domain/board/entity/Board.java
  server/src/main/java/com/growstory/domain/board/entity/Board_HashTag.java
  server/src/main/java/com/growstory/domain/board/repository/BoardHashTagRepository.java
  server/src/main/java/com/growstory/domain/board/repository/BoardHashTagResitory.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/comment/dto/CommentDto.java
  server/src/main/java/com/growstory/domain/comment/dto/ResponseCommentDto.java
  server/src/main/java/com/growstory/domain/comment/entity/Comment.java
  server/src/main/java/com/growstory/domain/comment/service/CommentService.java
  server/src/main/java/com/growstory/domain/hashTag/dto/ResponseHashTagDto.java
  server/src/main/java/com/growstory/domain/hashTag/repository/HashTagRepository.java
  server/src/main/java/com/growstory/domain/hashTag/service/HashTagService.java
  server/src/main/java/com/growstory/domain/images/service/BoardImageService.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
Labels: [BE] 황도경, Feature, Fix

#187 [BE] 🧪 Test : Account Controller 테스트
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
Labels: [BE] 김도형, Test

#188 🧪 Test : 정원 CRUD 관련 테스트 구현
  server/src/main/java/com/growstory/domain/journal/dto/JournalDto.java
  server/src/main/java/com/growstory/domain/plant_object/controller/PlantObjController.java
  server/src/main/java/com/growstory/domain/plant_object/dto/PlantObjDto.java
  server/src/main/java/com/growstory/domain/plant_object/mapper/PlantObjMapper.java
  server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
  server/src/main/java/com/growstory/domain/product/dto/ProductDto.java
  server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
  server/src/test/java/com/growstory/domain/plant_object/service/PlantObjServiceTest.java
  server/src/test/java/com/growstory/domain/stubdata/TestStubData.java
Labels: [BE] 이승태, Test

#189 [BE] 🐛 게시판 수정(이미지, 해시태그)
  server/src/main/java/com/growstory/domain/board/controller/BoardController.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/hashTag/repository/HashTagRepository.java
  server/src/main/java/com/growstory/domain/hashTag/service/HashTagService.java
  server/src/main/java/com/growstory/domain/images/repository/BoardImageRepository.java
  server/src/main/java/com/growstory/domain/images/service/BoardImageService.java
  server/src/test/java/com/growstory/domain/comment/controller/CommentControllerTest.java
Labels: [BE] 황도경, Fix

#192 [BE] 🧪 Test : 도형 - Account Controller 테스트, 도경 - Board, Hashtag 리팩토링, 승태 - PlantObj 테스트
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
Labels: [BE], Refactoring, Test

#185 [FE] ✨ board 페이지 비동기 요청 구현 및 스타일링
  client/package-lock.json
  client/src/api/board.ts
  client/src/app/board/layout.tsx
  client/src/app/board/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/components/board/BoardBanner.tsx
  client/src/components/board/BoardSearchInput.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/board/PostList.tsx
  client/src/components/board/RankBoard.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/post/Comment.tsx
  client/src/styles/globals.css
Labels: [FE], Styling, Feature

#193 [FE] ✨ Post의 add, edit 페이지, delete 기능 API 연결, ♻️ 기존 페이지 리팩토링
  client/package-lock.json
  client/public/assets/img/bg_default_profile.png
  client/src/api/post.ts
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/app/post/layout.tsx
  client/src/components/common/ErrorMessage.tsx
  client/src/components/common/ErrorNotice.tsx
  client/src/components/common/HeaderLink.tsx
  client/src/components/common/LoadingMessage.tsx
  client/src/components/common/LoadingNotice.tsx
  client/src/components/common/Preview.tsx
  client/src/components/garden/EditModeButton.tsx
  client/src/components/garden/GardenInfo.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSidebar.tsx
  client/src/components/garden/InstalledPlants.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/PurchaseInfoModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/garden/index.ts
  client/src/components/post/PostDeleteModal.tsx
  client/src/components/post/PostForm.tsx
  client/src/constants/contents.ts
  client/src/hooks/useGardenMap.ts
  client/src/hooks/usePurchasePlant.ts
  client/src/hooks/useSyncGarden.ts
  client/src/hooks/useTyping.ts
  client/src/stores/gardenStore.ts
  client/src/stores/userStore.ts
  client/src/types/data.d.ts
Labels: [FE], Refactoring, Styling, Add, Feature, Config

#196 [BE] 🧪 Test : 정원(Garden) 서비스 관련 유닛 테스트
  server/src/main/java/com/growstory/domain/comment/service/CommentService.java
  server/src/main/java/com/growstory/domain/journal/service/JournalService.java
  server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
  server/src/main/java/com/growstory/domain/plant_object/entity/PlantObj.java
  server/src/main/java/com/growstory/domain/plant_object/location/entity/Location.java
  server/src/main/java/com/growstory/domain/plant_object/mapper/PlantObjMapper.java
  server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
  server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/growstory/global/email/service/EmailService.java
  server/src/main/java/com/growstory/global/response/ErrorResponse.java
  server/src/main/resources/application.yml
  server/src/test/java/com/growstory/domain/plant_object/service/PlantObjServiceTest.java
  server/src/test/java/com/growstory/domain/stubdata/TestStubData.java
Labels: [BE] 이승태, Refactoring, Test, Fix

#199 [FE] ✨ 좋아요 기능 / ShareButton 구현 및 버그 및 스타일링 수정
  client/public/assets/icon/share.svg
  client/public/assets/img/checked.svg
  client/public/assets/img/unlike.svg
  client/src/api/board.ts
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/components/Leaf/Diary.tsx
  client/src/components/Leaf/DiaryForm.tsx
  client/src/components/Leaf/LeafDiary.tsx
  client/src/components/board/BoardSearchInput.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/board/PostList.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/common/ShareButton.tsx
  client/src/hooks/useGetBoardSearchQuery.ts
  client/src/hooks/useLikePostMutation.ts
  client/src/stores/boardStore.ts
  client/src/types/data.d.ts
Labels: [FE], Feature

#201 [FE] ✨ 2차 반응형 구현, ♻️ Post 페이지 관련 리팩토링
  client/src/api/post.ts
  client/src/app/board/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/app/profile/layout.tsx
  client/src/app/profile/page.tsx
  client/src/components/Leafs/AddLeafButton.tsx
  client/src/components/board/BoardBanner.tsx
  client/src/components/board/BoardSearchInput.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/board/PostList.tsx
  client/src/components/board/RankBoard.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/ImageUpload.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/PasswordInput.tsx
  client/src/components/common/TextArea.tsx
  client/src/components/common/TextInput.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSidebar.tsx
  client/src/components/garden/MapController.tsx
  client/src/components/garden/PlantCard.tsx
  client/src/components/garden/PurchaseModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/post/PostForm.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/profile/ProfileBox.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/hooks/useAddPost.ts
  client/src/hooks/useEditPost.ts
  client/src/utils/convertToFormData.ts
Labels: [FE], Refactoring, Styling, Feature

#202 [FE] ♻️ 페이지 리팩토링
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/components/Leaf/EmptyDiary.tsx
  client/src/components/Leaf/LeafInfo.tsx
  client/src/components/board/BoardBanner.tsx
  client/src/components/board/BoardSearchInput.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/post/PostProfile.tsx
Labels: [FE], Refactoring

#204 [FE] 💄 전체 CSS 다듬기
  client/src/app/board/layout.tsx
  client/src/app/board/page.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/components/Leaf/EmptyDiary.tsx
  client/src/components/Leaf/LeafInfo.tsx
  client/src/components/board/BoardBanner.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/board/PostList.tsx
  client/src/components/common/PasswordInput.tsx
  client/src/components/common/ShareButton.tsx
  client/src/components/garden/GardenInfo.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
Labels: [FE], Refactoring, Styling

#203 [FE] ✨ History 페이지 구현 완료
  client/src/api/history.ts
  client/src/api/profile.ts
  client/src/api/user.ts
  client/src/app/history/[id]/page.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/HeaderNav.tsx
  client/src/components/history/Dropdown.tsx
  client/src/components/history/FailureModal.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/history/UserButton.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/profile/ChangeNicknameModal.tsx
  client/src/components/profile/ChangePasswordModal.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/LoginButton.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/components/signin/SuccessedModal.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
  client/src/components/signup/SignButton.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/components/signup/SignupIntro.tsx
  client/src/stores/signStore.ts
  client/src/stores/userStore.ts
  client/src/types/common.d.ts
Labels: [FE], Feature

#205 [BE] ♻️ 게시판 상세 조회 리팩토링
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/board/controller/BoardController.java
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/board/dto/ResponseBoardDto.java
  server/src/main/java/com/growstory/domain/board/entity/Board.java
  server/src/main/java/com/growstory/domain/board/repository/BoardRepository.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/comment/dto/ResponseCommentDto.java
  server/src/main/java/com/growstory/domain/comment/service/CommentService.java
  server/src/main/java/com/growstory/domain/images/repository/BoardImageRepository.java
  server/src/main/java/com/growstory/domain/images/service/BoardImageService.java
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
Labels: [BE] 황도경, Fix

#207 [FE] ✨ 3차 반응형 구현, 기존 컴포넌트 스타일링 수정
  client/package-lock.json
  client/public/assets/img/hamburger.svg
  client/src/api/board.ts
  client/src/api/garden.ts
  client/src/api/leaf.ts
  client/src/api/post.ts
  client/src/app/board/page.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/Leaf/Diary.tsx
  client/src/components/Leaf/DiaryDeleteModal.tsx
  client/src/components/Leaf/DiaryForm.tsx
  client/src/components/Leaf/EmptyDiary.tsx
  client/src/components/Leaf/LeafDiary.tsx
  client/src/components/Leaf/LeafInfo.tsx
  client/src/components/Leaf/LeafModal.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/HeaderNav.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/Logo.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/PageTitle.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/post/ControlMenu.tsx
  client/src/components/post/PostDeleteModal.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/sign/SignInput.tsx
  client/src/components/sign/SignLink.tsx
  client/src/components/sign/SignModalInput.tsx
  client/src/components/sign/SignPasswordInput.tsx
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/LoginButton.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
  client/src/components/signup/SignButton.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/components/signup/SignupIntro.tsx
  client/src/hooks/useAddLeafMutaion.ts
  client/src/hooks/useConnectLeaf.ts
  client/src/hooks/useEditLeafMutation.ts
  client/src/hooks/useEditPost.ts
  client/src/stores/gardenStore.ts
  client/src/stores/leafsStore.ts
  client/src/stores/postStore.ts
  client/src/stores/testUserStore.ts
  client/src/utils/convertToFormData.ts
Labels: [FE], Refactoring, Styling, Add, Feature

#210 [BE] ♻️ Refactor : Account 관련 리팩토링
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/account/controller/AccountController.java
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/resources/application.yml
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
Labels: [BE] 김도형, Refactoring

#209 [FE] ♻️ Refactor: Header 정원, 식물카드 라우팅 수정, ImageForm 이슈
  client/src/components/common/Header.tsx
  client/src/components/common/PasswordInput.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/profile/ProfileBox.tsx
Labels: [FE], Refactoring, Fix

#211 [BE] 🧪 Test : PlantObjController API 테스트
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/plant_object/controller/PlantObjController.java
  server/src/test/java/com/growstory/domain/plant_object/controller/PlantObjectControllerTest.java
  server/src/test/java/com/growstory/domain/plant_object/service/PlantObjServiceTest.java
  server/src/test/java/com/growstory/domain/stubdata/Stub.java
Labels: [BE] 이승태, Refactoring, Test

#213 [FE] ✨ Garden 페이지 추가 기능 구현
  client/src/app/garden/[id]/page.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Logo.tsx
  client/src/components/garden/EditModeInfo.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/garden/GardenSidebar.tsx
  client/src/components/garden/MapController.tsx
  client/src/components/garden/PlantCard.tsx
  client/src/hooks/useGardenMap.ts
  client/src/hooks/useMouseDrag.ts
  client/src/hooks/usePlantCard.ts
Labels: [FE], Refactoring, Styling, Feature, Fix

#216 [FE] 💄 Leaf, board 관련 페이지 반응형 구현
  client/package-lock.json
  client/src/api/board.ts
  client/src/app/board/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/components/Leaf/Diary.tsx
  client/src/components/Leaf/DiaryDeleteModal.tsx
  client/src/components/Leaf/DiaryForm.tsx
  client/src/components/Leaf/LeafDateInfo.tsx
  client/src/components/Leaf/LeafModal.tsx
  client/src/components/Leafs/LeafDeleteModal.tsx
  client/src/components/board/EmptySearch.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/board/PostList.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/ShareButton.tsx
  client/src/components/common/ShareModal.tsx
  client/src/components/post/Comment.tsx
  client/src/components/post/CommentDeleteModal.tsx
  client/src/components/post/CommentForm.tsx
  client/src/components/post/DateAndControlSection.tsx
  client/src/hooks/useAddCommentMutation.ts
  client/src/hooks/useBoardInfinityQuery.ts
  client/src/hooks/useDeleteCommentMutation.ts
  client/src/hooks/useEditCommentMutation.ts
  client/src/hooks/useGetBoardSearchQuery.ts
  client/src/stores/leafStore.ts
  client/src/stores/leafsStore.ts
  client/src/utils/getTextInputTypeFormat.ts
  client/src/utils/setPreview.ts
Labels: [FE], Refactoring, Styling, Feature

#217 [FE] ✨ History 페이지 반응형 및 안내문 추가, 구글 로그인 다시 로드
  client/src/app/history/[id]/layout.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/components/Leaf/EmptyDiary.tsx
  client/src/components/history/ComfirmModal.tsx
  client/src/components/history/Dropdown.tsx
  client/src/components/history/FailureModal.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/HistoryPostCard.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/signin/LoginButton.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/constants/contents.ts
  client/src/utils/getTextInputTypeFormat.ts
Labels: [FE], Refactoring, Feature, Fix

#220 [FE] 💄 기존 페이지, 모달 컴포넌트 스타일링 수정
  client/src/app/page.tsx
  client/src/app/post/add/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/components/common/Intro.tsx
  client/src/components/common/Logo.tsx
  client/src/components/common/Modal.tsx
  client/src/components/garden/PurchaseInfoModal.tsx
  client/src/components/garden/PurchaseModal.tsx
Labels: [FE], Styling

#218 [FE] ✨ 공유하기 (leaf, leafs) 구현
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/components/common/ShareButton.tsx
Labels: [FE], Styling, Feature

#219 [FE] ♻️ History 페이지 반응형 작업중...
  client/src/components/Leaf/EmptyDiary.tsx
  client/src/components/history/ComfirmModal.tsx
  client/src/components/history/FailureModal.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/history/UserButton.tsx
  client/src/components/profile/ChangeNicknameModal.tsx
  client/src/components/profile/ChangePasswordModal.tsx
  client/src/components/sign/SignInput.tsx
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/SuccessedModal.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
Labels: [FE], Refactoring

#226 [FE] ✨ 정원 공유 기능 구현 및 좋아요 타입 오류 수정
  client/src/app/garden/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/components/common/ShareButton.tsx
  client/src/components/common/ShareModal.tsx
  client/src/components/garden/GardenInfo.tsx
  client/src/components/garden/GardenMap.tsx
  client/src/components/post/Comment.tsx
  client/src/components/post/CommentForm.tsx
  client/src/components/post/CommentProfileImage.tsx
  client/src/stores/gardenModalStore.ts
  client/src/types/data.d.ts
Labels: [FE], Feature, Fix

#227 [BE] ✨ 게시판 주간별 좋아요 랭킹 조회 API 구현
  server/src/main/java/com/growstory/GrowstoryApplication.java
  server/src/main/java/com/growstory/domain/board/controller/BoardController.java
  server/src/main/java/com/growstory/domain/board/dto/ResponseRankingDto.java
  server/src/main/java/com/growstory/domain/board/repository/BoardRepository.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/images/service/JournalImageService.java
  server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
  server/src/main/resources/application.yml
  server/src/test/java/com/growstory/domain/board/service/BoardRankingTest.java
  server/src/test/java/com/growstory/domain/journal/JournalControllerTest.java
  server/src/test/java/com/growstory/domain/stubdata/Stub.java
Labels: [BE], Feature

#229 [FE] 💄 History 페이지 반응형 구현
  client/src/components/common/Header.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/HistoryPostCard.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/leaf/EmptyDiary.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/SignupForm.tsx
Labels: [FE], Feature

#230 [FE] 💄 식물 관련 페이지 및 커뮤니티 페이지 반응형 수정 + form 이중 제출 방지
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/components/board/BoardSearchForm.tsx
  client/src/components/board/BoardSearchInput.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/ShareButton.tsx
  client/src/components/common/ShareModal.tsx
  client/src/components/leaf/Diary.tsx
  client/src/components/leaf/DiaryDeleteModal.tsx
  client/src/components/leaf/DiaryForm.tsx
  client/src/components/leaf/LeafModal.tsx
  client/src/components/leafs/LeafDeleteModal.tsx
  client/src/components/post/Comment.tsx
  client/src/components/post/CommentDeleteModal.tsx
  client/src/components/post/CommentForm.tsx
  client/src/components/post/ControlMenu.tsx
  client/src/components/post/DateAndControlSection.tsx
  client/src/components/post/PostContent.tsx
  client/src/components/post/PostDeleteModal.tsx
  client/src/components/post/PostForm.tsx
  client/src/components/post/PostProfile.tsx
Labels: [FE], Styling, Feature, Fix

#232 [BE] ♻️ Refactor : Security 리팩토링
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/comment/entity/Comment.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/domain/likes/entity/BoardLike.java
  server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java
  server/src/main/java/com/growstory/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/growstory/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/java/com/growstory/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
  server/src/test/java/com/growstory/domain/leaf/controller/LeafControllerTest.java
  server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java
Labels: [BE] 김도형, Refactoring

#233 [BE] ♻️ Refactor : Leaf 리팩토링
  server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java
Labels: [BE] 김도형, Refactoring

#235 [BE] ♻️ Refactor : Leaf 리팩토링
  server/src/main/resources/application.yml
Labels: [BE] 김도형, Refactoring

#236 [BE] ♻️ Refactor : Leaf 리팩토링
  server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java
Labels: [BE] 김도형

#237 [BE] ♻️ Refactor : Leaf 리팩토링
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
  server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java
Labels: [BE] 김도형, Refactoring

#234 [FE] ✨ 메인 관련 컴포넌트 구현
  client/public/assets/icon/scroll_down.svg
  client/public/assets/img/no_border_tree.svg
  client/src/components/common/LeafForm.tsx
  client/src/components/main/ MainSignupBanner.tsx
  client/src/components/main/ScrollDownButton.tsx
Labels: [FE], Add, Feature

#242 [FE] ✨ Main 페이지 구현, 전체 페이지 스타일링 다듬기
  client/src/app/history/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/page.tsx
  client/src/app/profile/page.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/common/ErrorNotice.tsx
  client/src/components/common/Intro.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/LoadingNotice.tsx
  client/src/components/garden/InstalledPlants.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/MapController.tsx
  client/src/components/garden/NoLeafExistModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/leaf/Diary.tsx
  client/src/components/leaf/DiaryForm.tsx
  client/src/components/main/MainSignupBanner.tsx
  client/src/components/main/ScrollDownButton.tsx
  client/src/components/main/ServiceInfo.tsx
  client/src/components/post/ControlMenu.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/SuccessedModal.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
  client/src/hooks/useMainPageButtonAnimation.ts
  client/src/styles/globals.css
Labels: [FE], Refactoring, Styling, Feature, Fix

#243 ✨ Feat : 주차별 게시글 '좋아요' 랭킹 조회 및 보상 기능 구현
  server/src/main/java/com/growstory/domain/board/controller/BoardController.java
  server/src/main/java/com/growstory/domain/board/dto/BoardLikesRankDto.java
  server/src/main/java/com/growstory/domain/board/dto/ResponseRankingDto.java
  server/src/main/java/com/growstory/domain/board/repository/BoardRepository.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/domain/rank/RankService.java
  server/src/main/java/com/growstory/domain/rank/board_likes/dto/BoardLikesRankDto.java
  server/src/main/java/com/growstory/domain/rank/board_likes/entity/BoardLikesRank.java
  server/src/main/java/com/growstory/domain/rank/board_likes/history/entity/BoardLikesRankHistory.java
  server/src/main/java/com/growstory/domain/rank/board_likes/history/repository/BoardLikesRankHistoryRepository.java
  server/src/main/java/com/growstory/domain/rank/board_likes/repository/BoardLikesRankRepository.java
  server/src/main/java/com/growstory/domain/rank/board_likes/service/BoardLikesRankService.java
  server/src/main/java/com/growstory/domain/rank/controller/RankController.java
  server/src/main/java/com/growstory/domain/rank/entity/Rank.java
  server/src/main/java/com/growstory/global/exception/ExceptionCode.java
  server/src/main/resources/application-prod.yml
  server/src/test/java/com/growstory/domain/board/service/BoardRankingTest.java
Labels: [BE] 이승태

#244 [FE] 🔧 이미지 흐림 방지 관련 전역 스타일 추가
  client/src/components/common/Header.tsx
  client/src/styles/globals.css
Labels: [FE], Styling, Config

#245 [BE] ♻️ Refactor : Security 리팩토링
  .github/workflows/server.yml
  server/src/main/java/com/growstory/HelloController.java
  server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
  server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountFailureHandler.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/resources/application-prod.yml
  server/src/main/resources/keystore.p12
  server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java
Labels: [BE] 김도형, Refactoring

#246 [FE] 🐛 History 반응형, api에 refreshToken 추가
  client/src/api/history.ts
  client/src/api/profile.ts
  client/src/api/user.ts
  client/src/components/common/SeoHead.tsx
  client/src/components/history/ComfirmModal.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/HistoryPostCard.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/profile/ProfileBox.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/LoginButton.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/constants/contents.ts
  client/src/hooks/useGetMetaData.ts
  client/src/stores/userStore.ts
  client/src/types/common.d.ts
Labels: [FE], Fix

#247 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/api/history.ts
  client/src/api/profile.ts
  client/src/api/user.ts
  client/src/app/history/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/page.tsx
  client/src/app/profile/page.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/common/ErrorNotice.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Intro.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/LoadingNotice.tsx
  client/src/components/common/SeoHead.tsx
  client/src/components/garden/InstalledPlants.tsx
  client/src/components/garden/LeafExistModal.tsx
  client/src/components/garden/MapController.tsx
  client/src/components/garden/NoLeafExistModal.tsx
  client/src/components/garden/SelectLeafModal.tsx
  client/src/components/history/ComfirmModal.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/HistoryPostCard.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/leaf/Diary.tsx
  client/src/components/leaf/DiaryForm.tsx
  client/src/components/main/MainSignupBanner.tsx
  client/src/components/main/ScrollDownButton.tsx
  client/src/components/main/ServiceInfo.tsx
  client/src/components/post/ControlMenu.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/NicknameForm.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/profile/ProfileBox.tsx
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/LoginButton.tsx
  client/src/components/signin/SigninForm.tsx
  client/src/components/signin/SuccessedModal.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
  client/src/constants/contents.ts
  client/src/hooks/useGetMetaData.ts
  client/src/hooks/useMainPageButtonAnimation.ts
  client/src/stores/userStore.ts
  client/src/styles/globals.css
  client/src/types/common.d.ts
Labels: [FE], Deploy

#248 [FE] 🐛 Fix: 게시글 이미지 이슈 해결
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/UserInfo.tsx
Labels: [FE], Fix

#249 [FE] 🐛 Garden 페이지 포인트 관련 이슈 해결
  client/src/hooks/usePlantCard.ts
Labels: [FE], Fix

#250 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/UserInfo.tsx
  client/src/hooks/usePlantCard.ts
Labels: [FE], Deploy

#253 [FE] 🐛 Board 페이지 반응형 이슈 해결
  client/src/components/board/RankBoard.tsx
Labels: [FE], Fix

#254 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/components/board/RankBoard.tsx
Labels: [FE], Deploy

#255 [FE] 💄 History Style 수정
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
Labels: [FE], Fix

#256 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
Labels: [FE], Deploy

#260 [FE] 🐛 통합 테스트 후 버그 수정
  client/public/assets/img/bg_default_post.png
  client/src/app/garden/[id]/page.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/not-found.tsx
  client/src/app/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/app/profile/page.tsx
  client/src/components/board/PostCard.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Intro.tsx
  client/src/components/common/Leaf.tsx
  client/src/components/common/PageTitle.tsx
  client/src/components/common/TextArea.tsx
  client/src/components/history/ConfirmModal.tsx
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/history/HistoryPostCard.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/UserButton.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/leaf/Diary.tsx
  client/src/components/post/CommentProfileImage.tsx
  client/src/components/post/HashTags.tsx
  client/src/components/post/PostContent.tsx
  client/src/components/post/PostImage.tsx
  client/src/components/post/PostProfile.tsx
  client/src/components/profile/ImageForm.tsx
  client/src/components/profile/ProfileBox.tsx
  client/src/hooks/useEditPost.ts
  client/src/mock/board.json
  client/src/mock/diary.json
  client/src/mock/garden.json
  client/src/mock/leaf.json
  client/src/styles/globals.css
Labels: [FE], Refactoring, Add, Feature, Fix

#263 [FE] ✨ Footer 컴포넌트 구현
  client/public/assets/img/footer_github.png
  client/src/app/board/page.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/app/profile/page.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/FooterLink.tsx
  client/src/components/profile/ChangeNicknameModal.tsx
  client/src/components/profile/ChangePasswordModal.tsx
  client/src/constants/contents.ts
Labels: [FE], Add, Feature, Fix

#264 [FE] 💄 board rank 글자 색 수정
  client/src/components/board/RankBoard.tsx
Labels: [FE], Styling

#266 [FE] ✨ 전체 페이지 Metadata 적용
  client/public/assets/img/favicon.png
  client/src/app/board/layout.tsx
  client/src/app/board/page.tsx
  client/src/app/garden/[id]/layout.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/history/[id]/layout.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/layout.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/leaf/add/[userId]/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leaf/layout.tsx
  client/src/app/leafs/[id]/layout.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/app/post/edit/[id]/page.tsx
  client/src/app/post/layout.tsx
  client/src/app/profile/layout.tsx
  client/src/app/profile/page.tsx
  client/src/app/signin/layout.tsx
  client/src/app/signup/layout.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/FooterLink.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/history/Dropdown.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/post/CommentProfileImage.tsx
  client/src/components/post/PostImage.tsx
  client/src/components/post/PostProfile.tsx
Labels: [FE], Styling, Add, Feature, Fix

#269 [FE] 🐛 board 랭크 기능 버그 fix
  client/src/components/board/RankBoard.tsx
  client/src/hooks/useBoardInfinityQuery.ts
Labels: [FE]

#270 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/components/board/RankBoard.tsx
  client/src/hooks/useBoardInfinityQuery.ts
Labels: [FE], Deploy

#271 [FE] 🐛 3차 테스트 후 발생한 오류 수정
  client/src/components/common/Footer.tsx
  client/src/components/common/FooterLink.tsx
  client/src/components/common/Preview.tsx
  client/src/components/profile/ChangeNicknameModal.tsx
  client/src/components/profile/ChangePasswordModal.tsx
  client/src/components/signin/SigninForm.tsx
Labels: [FE], Styling, Fix

#272 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/components/common/Footer.tsx
  client/src/components/common/FooterLink.tsx
  client/src/components/common/Preview.tsx
  client/src/components/profile/ChangeNicknameModal.tsx
  client/src/components/profile/ChangePasswordModal.tsx
  client/src/components/signin/SigninForm.tsx
Labels: [FE], Deploy

#274 [FE/BE] 📝 README.md 파일 내용 업데이트
  README.md
Labels: Document

#277 ♻️ Refactor : 게시글 상세 페이지 게스트 허용
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/board/repository/BoardRepository.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/rank/board_likes/entity/BoardLikesRank.java
  server/src/main/java/com/growstory/domain/rank/board_likes/history/entity/BoardLikesRankHistory.java
  server/src/main/java/com/growstory/domain/rank/board_likes/service/BoardLikesRankService.java
  server/src/main/java/com/growstory/domain/rank/entity/Rank.java
  server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
  server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
  server/src/test/java/com/growstory/domain/board/service/BoardServiceTest.java
Labels: [BE], Refactoring

#279 ♻️ Refactor: 게시판 이슈 해결
  .github/workflows/server.yml
  server/Dockerfile
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/board/entity/Board.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/resources/application-prod.yml
  server/src/test/java/com/growstory/domain/board/controller/BoardControllerTest.java
Labels: [BE] 황도경, [BE], Refactoring

#280 [FE] ♻️ 게시글 상세 페이지 비로그인 뷰 관련 수정
  client/src/app/post/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/components/board/RankBoard.tsx
  client/src/components/common/PostCountInfo.tsx
Labels: [FE], Refactoring

#281 [FE] ✨ Main 페이지 이미지 추가
  client/public/assets/img/temporal_img.png
  client/src/app/globals.css
  client/src/components/main/ServiceInfo.tsx
Labels: [FE], Feature

#282 [FE] 🚀 배포를 위한 브랜치 병합
  client/public/assets/img/temporal_img.png
  client/src/app/globals.css
  client/src/app/post/[id]/page.tsx
  client/src/app/post/add/page.tsx
  client/src/components/board/RankBoard.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/main/ServiceInfo.tsx
Labels: [FE], Deploy

#283 [FE] 🐛 alert 관련 이슈 해결
  client/src/app/post/add/page.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/signup/AuthEmailModal.tsx
Labels: [FE], Feature, Fix

#284 [FE] ✨ 관리자 ID인 경우 조건부 렌더링 추가
  client/src/api/board.ts
  client/src/api/garden.ts
  client/src/api/history.ts
  client/src/api/leaf.ts
  client/src/api/post.ts
  client/src/api/profile.ts
  client/src/app/post/add/page.tsx
  client/src/app/profile/page.tsx
  client/src/components/common/HeaderNav.tsx
  client/src/components/common/PostCountInfo.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/profile/ProfileBox.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/constants/values.ts
  client/src/stores/userStore.ts
Labels: [FE], Refactoring, Feature, Fix

#285 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/api/board.ts
  client/src/api/garden.ts
  client/src/api/history.ts
  client/src/api/leaf.ts
  client/src/api/post.ts
  client/src/api/profile.ts
  client/src/app/profile/page.tsx
  client/src/components/common/HeaderNav.tsx
  client/src/components/history/HistoryBox.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/profile/ProfileBox.tsx
  client/src/constants/values.ts
  client/src/stores/userStore.ts
Labels: [FE], Deploy

#286 [FE] 🐛 이미지 컴포넌트 관련 이슈, 공유 버튼 이슈 해결
  client/src/components/board/PostCard.tsx
  client/src/components/common/ShareButton.tsx
  client/src/components/main/ServiceInfo.tsx
  client/src/constants/values.ts
Labels: [FE], Refactoring, Feature, Fix

#291 [BE] ♻️ Refactor : 이메일 로직 개선, 비동기 처리2
  .github/workflows/server.yml
  server/Dockerfile
  server/src/main/java/com/growstory/GrowstoryApplication.java
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/board/entity/Board.java
  server/src/main/java/com/growstory/domain/board/repository/BoardRepository.java
  server/src/main/java/com/growstory/domain/board/service/BoardService.java
  server/src/main/java/com/growstory/domain/rank/board_likes/entity/BoardLikesRank.java
  server/src/main/java/com/growstory/domain/rank/board_likes/history/entity/BoardLikesRankHistory.java
  server/src/main/java/com/growstory/domain/rank/board_likes/service/BoardLikesRankService.java
  server/src/main/java/com/growstory/domain/rank/entity/Rank.java
  server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java
  server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
  server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
  server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
  server/src/main/java/com/growstory/global/email/service/EmailService.java
  server/src/main/resources/application-prod.yml
  server/src/test/java/com/growstory/GrowstoryApplicationTests.java
  server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
  server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
  server/src/test/java/com/growstory/domain/board/service/BoardRankingTest.java
  server/src/test/java/com/growstory/domain/board/service/BoardServiceTest.java
  server/src/test/java/com/growstory/domain/comment/controller/CommentControllerTest.java
  server/src/test/java/com/growstory/domain/journal/JournalControllerTest.java
  server/src/test/java/com/growstory/domain/leaf/controller/LeafControllerTest.java
  server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java
  server/src/test/java/com/growstory/domain/plant_object/controller/PlantObjectControllerTest.java
  server/src/test/java/com/growstory/domain/plant_object/service/PlantObjServiceTest.java
  server/src/test/java/com/growstory/domain/stubdata/Stub.java
  server/src/test/java/com/growstory/global/customUser/annotation/WithMockCustomUser.java
  server/src/test/java/com/growstory/global/customUser/factory/WithMockCustomUserSecurityContextFactory.java
Labels: [BE], Feature

#292 [BE] ♻️ Refactor : 이메일 로직 개선, 비동기 처리3
  server/src/main/java/com/growstory/GrowstoryApplication.java
  server/src/main/java/com/growstory/global/email/service/EmailService.java
Labels: [BE], Refactoring
