Repository codestates-seb/seb45_main_011, pull requests merged in 2023-12, with the labels that each got.

#341 [BE] ✨ 실시간 채팅 구현
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/constant/ChatMessageConstants.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageStompController.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageService.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageServiceImpl.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/controller/ChatRoomController.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/ChatRoomResponseDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/CreateQnaChatRequest.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/SimpChatRoomRequestDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/entity/ChatRoom.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomService.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomServiceImpl.java
  server/src/main/java/com/growstory/global/email/controller/EmailController.java
  server/src/main/java/com/growstory/global/email/dto/EmailDto.java
  server/src/main/java/com/growstory/global/email/service/EmailService.java
  server/src/main/resources/templates/qnaResponse.html
Labels: [BE] 이승태, Refactoring, Feature

#342 [BE] ✨ 실시간 채팅 구현
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/qnachat/chatroom/controller/ChatRoomController.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/ChatRoomResponseDto.java
  server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomServiceImpl.java
Labels: [BE] 이승태, Refactoring, Fix

#336 [FE] ✨ 활동 기록 알림 구현 및 식물 일지 response 수정
  client/public/assets/icon/notification.svg
  client/src/api/board.ts
  client/src/api/leaf.ts
  client/src/api/notification.ts
  client/src/app/board/page.tsx
  client/src/app/leaf/edit/[userId]/[leafId]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/components/board/RankBoard.tsx
  client/src/components/common/ControlButton.tsx
  client/src/components/common/ImageUpload.tsx
  client/src/components/common/LeafForm.tsx
  client/src/components/common/NotificationButton.tsx
  client/src/components/common/NotificationMessage.tsx
  client/src/components/common/NotificationPanel.tsx
  client/src/components/common/SeoHead.tsx
  client/src/components/common/index.ts
  client/src/components/leafs/LeafDeleteModal.tsx
  client/src/constants/contents.ts
  client/src/hooks/mutation/useDeleteAllNotificationMutation.ts
  client/src/hooks/mutation/useDeleteNotificationMutation.ts
  client/src/hooks/mutation/useShowNotificationMutation.ts
  client/src/hooks/query/useLeafQuery.ts
  client/src/hooks/query/useNotificationsQuery.ts
  client/src/stores/notificationStore.ts
  client/src/types/data.d.ts
  client/src/utils/convertToFormData.ts
Labels: [FE], Refactoring, Styling, Feature

#345 ✨ 게스트 모드 로그인 & 로그아웃, 관리자와 유저의 실시간 문의 채팅 구현
  client/package-lock.json
  client/package.json
  client/src/api/axios.ts
  client/src/api/chat.ts
  client/src/api/guest.ts
  client/src/api/localStorage.ts
  client/src/app/admin/layout.tsx
  client/src/app/admin/page.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/admin/ChatModal.tsx
  client/src/components/admin/CheckInquiry.tsx
  client/src/components/admin/InquiryListForm.tsx
  client/src/components/admin/Pagination.tsx
  client/src/components/admin/index.ts
  client/src/components/common/Header.tsx
  client/src/components/common/HeaderNav.tsx
  client/src/components/common/Modal.tsx
  client/src/components/garden/EditModeButton.tsx
  client/src/components/history/HistoryLikes.tsx
  client/src/components/inquiry/Chat.tsx
  client/src/components/inquiry/ChatBox.tsx
  client/src/components/inquiry/ChatInput.tsx
  client/src/components/inquiry/InquiryForm.tsx
  client/src/components/inquiry/InquiryHome.tsx
  client/src/components/inquiry/InquiryList.tsx
  client/src/components/inquiry/InquiryRoom.tsx
  client/src/components/inquiry/NewChat.tsx
  client/src/components/inquiry/TitleInput.tsx
  client/src/components/inquiry/index.ts
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/LoginButton.tsx
  client/src/components/signin/MembershipCheckModal.tsx
  client/src/components/signin/index.ts
  client/src/components/signup/MembershipCheckModal.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/components/signup/index.ts
  client/src/constants/contents.ts
  client/src/hooks/mutation/useAuthEmailMutation.ts
  client/src/hooks/mutation/useChangeImageMutation.ts
  client/src/hooks/mutation/useChangePasswordMutation.ts
  client/src/hooks/mutation/useCreateChatRoomMutation.ts
  client/src/hooks/mutation/useCreateGuestMutation.ts
  client/src/hooks/mutation/useDeleteGuestMutation.ts
  client/src/hooks/mutation/useDeleteUserMutation.ts
  client/src/hooks/mutation/useUpdateChatAnsweredMutation.ts
  client/src/hooks/query/useChatListQuery.ts
  client/src/hooks/query/useChatMessageQuery.ts
  client/src/hooks/query/useInquiryListPaginationQuery.ts
  client/src/hooks/useFindPassword.ts
  client/src/hooks/usePagination.ts
  client/src/hooks/usePlantCard.ts
  client/src/stores/chatStore.ts
  client/src/stores/modalStore.ts
  client/src/stores/userStore.ts
  client/src/types/data.d.ts
Labels: Refactoring, Feature, Fix

#351 [FE] 🐛 모달 컴포넌트 이슈 해결
  client/src/app/history/[id]/page.tsx
  client/src/app/profile/page.tsx
  client/src/app/signin/page.tsx
  client/src/app/signup/page.tsx
  client/src/components/history/ConfirmModal.tsx
  client/src/components/history/FailureModal.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/profile/ChangeProfileModal.tsx
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/MembershipCheckModal.tsx
  client/src/components/signin/SuccessedModal.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
  client/src/components/signup/MembershipCheckModal.tsx
  client/src/constants/values.ts
  client/src/hooks/useModal.ts
Labels: Refactoring, Fix

#353 [FE] ✨ Garden 페이지 방명록 구현
  client/src/api/garden.ts
  client/src/app/garden/[id]/page.tsx
  client/src/components/garden/Comment.tsx
  client/src/components/garden/CommentForm.tsx
  client/src/components/garden/CommentProfileImage.tsx
  client/src/components/garden/GuestbookModal.tsx
  client/src/components/garden/index.ts
  client/src/components/post/DateAndControlSection.tsx
  client/src/hooks/mutation/useAddGuestbookMutation.ts
  client/src/stores/modalStore.ts
  client/src/types/data.d.ts
Labels: [FE], Styling, Feature, Fix

#354 ♻️ Refactor: 게스트 계정 생성 로직 변경, 방명록 조회 로직 변경
  .github/workflows/server.yml
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/guest/service/GuestService.java
  server/src/main/java/com/growstory/domain/guestbook/dto/GuestBookResponseDto.java
  server/src/main/java/com/growstory/domain/guestbook/service/GuestBookService.java
Labels: [BE] 황도경, [BE], Refactoring, Fix

#347 [BE] ✨ 실시간 채팅 구현
  server/src/main/java/com/growstory/domain/account/entity/Account.java
  server/src/main/java/com/growstory/domain/account/service/AccountService.java
  server/src/main/java/com/growstory/domain/journal/service/JournalService.java
  server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
  server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageServiceImpl.java
  server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/growstory/global/response/ErrorResponse.java
  server/src/main/java/com/growstory/global/websocket/FilterChannelInterceptor.java
Labels: [BE] 이승태, Refactoring, Feature, Fix

#356 [FE] 게스트 모드 로그아웃 토큰 이슈 해결 및 InquiryButton 컴포넌트 구현
  client/public/assets/icon/qna.svg
  client/src/api/axios.ts
  client/src/api/chat.ts
  client/src/api/guest.ts
  client/src/app/board/page.tsx
  client/src/app/garden/[id]/page.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/leafs/[id]/page.tsx
  client/src/app/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/app/profile/page.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/HeaderNav.tsx
  client/src/components/common/NotificationButton.tsx
  client/src/components/inquiry/Chat.tsx
  client/src/components/inquiry/InquiryButton.tsx
  client/src/components/inquiry/InquiryForm.tsx
  client/src/components/inquiry/InquiryHome.tsx
  client/src/components/inquiry/InquiryRoom.tsx
  client/src/components/inquiry/index.ts
  client/src/hooks/mutation/useCreateGuestMutation.ts
  client/src/hooks/mutation/useSigninMutation.ts
  client/src/stores/chatStore.ts
  client/src/stores/userStore.ts
  client/src/utils/checkForToken.ts
Labels: Add, Feature, Fix

#357 ♻️ Refactor: 방명록 조회 최신순 정렬
  server/src/main/java/com/growstory/domain/guestbook/service/GuestBookService.java
Labels: [BE] 황도경, Refactoring

#360 [FE] ✨ access, refresh token 만료 시 로그아웃 처리 구현
  client/src/api/axios.ts
  client/src/components/common/SeoHead.tsx
  client/src/components/history/FailureModal.tsx
  client/src/components/history/HistoryPostCard.tsx
  client/src/components/history/ResignModal.tsx
  client/src/components/history/SuccessedModal.tsx
  client/src/components/history/UserInfo.tsx
  client/src/components/inquiry/Chat.tsx
  client/src/components/inquiry/InquiryHome.tsx
  client/src/components/inquiry/InquiryRoom.tsx
  client/src/components/inquiry/NewChat.tsx
  client/src/components/profile/PasswordForm.tsx
  client/src/components/profile/ProfileBox.tsx
  client/src/components/sign/SignLink.tsx
  client/src/components/signin/FailureModal.tsx
  client/src/components/signin/FindPasswordModal.tsx
  client/src/components/signin/SigninIntro.tsx
  client/src/components/signin/SuccessedModal.tsx
  client/src/components/signup/AuthEmailModal.tsx
  client/src/components/signup/FailureModal.tsx
  client/src/components/signup/SignButton.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/components/signup/SignupIntro.tsx
  client/src/types/common.d.ts
  client/src/utils/checkForToken.ts
Labels: Refactoring, Feature, Fix

#364 [FE] 🐛 프론트 배포 이슈 해결
  client/src/components/common/index.ts
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
Labels: [FE], Fix

#365 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/components/common/index.ts
  client/src/components/history/HistoryBoard.tsx
  client/src/components/history/HistoryComment.tsx
  client/src/components/history/HistoryLikes.tsx
Labels: [FE], Deploy

#366 [FE] 🐛 프론트 배포 이슈 해결
  client/src/components/garden/Comment.tsx
Labels: [FE], Fix

#367 [FE] ✨ 모든 페이지에 알림 버튼 추가
  client/src/app/garden/[id]/page.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/page.tsx
  client/src/app/profile/page.tsx
Labels: [FE], Feature

#368 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/app/garden/[id]/page.tsx
  client/src/app/history/[id]/page.tsx
  client/src/app/page.tsx
  client/src/app/profile/page.tsx
  client/src/components/garden/Comment.tsx
Labels: [FE], Deploy

#369 [FE] 🐛 웹소켓 콘솔 관련 이슈 해결
  client/next.config.js
Labels: [FE], Fix

#370 [FE] 🚀 배포를 위한 브랜치 병합
  client/next.config.js
Labels: [FE], Deploy
