Repository codestates-seb/seb45_main_011, pull requests merged in 2024-04, with the labels that each got.

#384 [FE] 🐛 배포 관련 이슈 해결
  client/src/app/garden/[id]/page.tsx
Labels: Fix, Deploy

#383 [FE] 🚑 회원가입 시 이메일 인증 코드를 두 번 보내는 이슈 및 페이지 접근 권한 설정
  client/package-lock.json
  client/package.json
  client/src/api/axios.ts
  client/src/api/guest.ts
  client/src/components/admin/ChatModal.tsx
  client/src/components/admin/CheckInquiry.tsx
  client/src/components/admin/InquiryTable.tsx
  client/src/components/admin/index.ts
  client/src/components/inquiry/Chat.tsx
  client/src/components/inquiry/ChatBox.tsx
  client/src/components/inquiry/ChatInput.tsx
  client/src/components/inquiry/InquiryButton.tsx
  client/src/components/inquiry/InquiryForm.tsx
  client/src/components/inquiry/InquiryHome.tsx
  client/src/components/inquiry/InquiryList.tsx
  client/src/components/inquiry/NewChat.tsx
  client/src/components/inquiry/TitleInput.tsx
  client/src/components/sign/SignTextInput.tsx
  client/src/components/sign/index.ts
  client/src/components/signin/SigninForm.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/constants/values.ts
  client/src/hooks/mutation/useCreateGuestMutation.ts
  client/src/hooks/mutation/useDeleteGuestMutation.ts
  client/src/hooks/mutation/useDeleteUserMutation.ts
  client/src/hooks/mutation/useSigninMutation.ts
  client/src/hooks/query/useChatListQuery.ts
  client/src/hooks/useGoogleLogin.ts
  client/src/hooks/useNewChatAndExistChatConnect.ts
  client/src/middleware.ts
  client/src/stores/chatStore.ts
  client/src/types/data.d.ts
  client/src/utils/removeCookiesForUserId.ts
  client/src/utils/setCookiesByUserId.ts
Labels: Refactoring, Fix

#385 [FE] 🚀 배포를 위한 브랜치 병합
  client/package-lock.json
  client/package.json
  client/src/api/axios.ts
  client/src/api/guest.ts
  client/src/app/garden/[id]/page.tsx
  client/src/components/admin/ChatModal.tsx
  client/src/components/admin/CheckInquiry.tsx
  client/src/components/admin/InquiryTable.tsx
  client/src/components/admin/index.ts
  client/src/components/inquiry/Chat.tsx
  client/src/components/inquiry/ChatBox.tsx
  client/src/components/inquiry/ChatInput.tsx
  client/src/components/inquiry/InquiryButton.tsx
  client/src/components/inquiry/InquiryForm.tsx
  client/src/components/inquiry/InquiryHome.tsx
  client/src/components/inquiry/InquiryList.tsx
  client/src/components/inquiry/NewChat.tsx
  client/src/components/inquiry/TitleInput.tsx
  client/src/components/sign/SignTextInput.tsx
  client/src/components/sign/index.ts
  client/src/components/signin/SigninForm.tsx
  client/src/components/signup/SignupForm.tsx
  client/src/constants/values.ts
  client/src/hooks/mutation/useCreateGuestMutation.ts
  client/src/hooks/mutation/useDeleteGuestMutation.ts
  client/src/hooks/mutation/useDeleteUserMutation.ts
  client/src/hooks/mutation/useSigninMutation.ts
  client/src/hooks/query/useChatListQuery.ts
  client/src/hooks/useGoogleLogin.ts
  client/src/hooks/useNewChatAndExistChatConnect.ts
  client/src/middleware.ts
  client/src/stores/chatStore.ts
  client/src/types/data.d.ts
  client/src/utils/removeCookiesForUserId.ts
  client/src/utils/setCookiesByUserId.ts
Labels: [FE], Deploy

#386 [FE] 🐛 배포 관련 이슈 해결
  client/src/app/page.tsx
Labels: [FE], Fix, Deploy

#387 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/app/page.tsx
Labels: [FE], Deploy
