Repository codestates-seb/seb45_main_011, pull requests merged in 2024-01, with the labels that each got.

#371 [BE] ♻️ 주간별 게시판 좋아요 랭킹 조회 API 리팩토링
  .github/workflows/server.yml
  server/server_log
  server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
  server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
  server/src/main/java/com/growstory/domain/comment/dto/CommentDto.java
  server/src/main/java/com/growstory/domain/journal/dto/JournalDto.java
  server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
  server/src/main/java/com/growstory/domain/point/service/PointService.java
  server/src/main/java/com/growstory/domain/rank/board_likes/service/BoardLikesRankService.java
  server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/growstory/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/growstory/global/badwords/filterlist/WhiteList.java
  server/src/main/java/com/growstory/global/badwords/service/BlackListService.java
  server/src/main/java/com/growstory/global/badwordsfilter/aspect/BadWordsAspect.java
  server/src/main/java/com/growstory/global/badwordsfilter/dto/ProfanityResponse.java
  server/src/main/java/com/growstory/global/badwordsfilter/dto/TextContainer.java
  server/src/main/java/com/growstory/global/badwordsfilter/filterlist/AllowedWords.java
  server/src/main/java/com/growstory/global/badwordsfilter/filterlist/BadWords.java
  server/src/main/java/com/growstory/global/badwordsfilter/service/BadWordsService.java
  server/src/main/java/com/growstory/global/exception/BusinessLogicException.java
  server/src/main/java/com/growstory/global/response/ErrorResponse.java
  server/src/main/java/com/growstory/global/websocket/FilterChannelInterceptor.java
  server/src/main/resources/application-test.yml
  server/src/main/resources/keystore.p12
  server/src/test/java/com/growstory/global/badwordsfilter/service/BadWordsServiceTest.java
Labels: [BE] 이승태

#376 [FE] 🚀 배포를 위한 브랜치 병합
  client/src/components/inquiry/Chat.tsx
  client/src/components/inquiry/NewChat.tsx
Labels: [FE], Deploy

#378 [FE]♻️ 이미지 사이즈 제한 조정
  client/package-lock.json
  client/src/app/garden/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/constants/contents.ts
  client/src/utils/isValidFileSize.ts
Labels: [FE], Refactoring

#379 [FE] 🚀 배포를 위한 브랜치 병합
  client/package-lock.json
  client/src/app/garden/[id]/page.tsx
  client/src/app/leaf/[userId]/[leafId]/page.tsx
  client/src/app/page.tsx
  client/src/app/post/[id]/page.tsx
  client/src/constants/contents.ts
  client/src/utils/isValidFileSize.ts
Labels: [FE], Deploy
